/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace OSGeo.GDAL {

public enum RATFieldUsage {
  GFU_Generic = 0,
  GFU_PixelCount = 1,
  GFU_Name = 2,
  GFU_Min = 3,
  GFU_Max = 4,
  GFU_MinMax = 5,
  GFU_Red = 6,
  GFU_Green = 7,
  GFU_Blue = 8,
  GFU_Alpha = 9,
  GFU_RedMin = 10,
  GFU_GreenMin = 11,
  GFU_BlueMin = 12,
  GFU_AlphaMin = 13,
  GFU_RedMax = 14,
  GFU_GreenMax = 15,
  GFU_BlueMax = 16,
  GFU_AlphaMax = 17,
  GFU_MaxCount
}

}
