/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace OSGeo.GDAL {

public enum ResampleAlg {
  GRA_NearestNeighbour = 0,
  GRA_Bilinear = 1,
  GRA_Cubic = 2,
  GRA_CubicSpline = 3
}

}
