/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace OSGeo.GDAL {

public enum XMLNodeType {
  CXT_Element = 0,
  CXT_Text = 1,
  CXT_Attribute = 2,
  CXT_Comment = 3,
  CXT_Literal = 4
}

}
