######################################################################
# Automatically generated by qmake (2.01a) ds. de maig 24 11:23:11 2014
######################################################################

CONFIG += qtestlib
QMAKE_CXXFLAGS += -std=c++11
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
INCLUDEPATH += ../../

LIBS += -lboost_filesystem -lboost_system
# Input
HEADERS += CassandraTests.hxx
SOURCES += CassandraTests.cxx ../../TimeSeriesModel.cxx
