/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace OSGeo.OGR {

public enum wkbGeometryType {
  wkbUnknown = 0,
  wkbPoint = 1,
  wkbLineString = 2,
  wkbPolygon = 3,
  wkbMultiPoint = 4,
  wkbMultiLineString = 5,
  wkbMultiPolygon = 6,
  wkbGeometryCollection = 7,
  wkbNone = 100,
  wkbLinearRing = 101,
  wkbPoint25D = -2147483647,
  wkbLineString25D = -2147483646,
  wkbPolygon25D = -2147483645,
  wkbMultiPoint25D = -2147483644,
  wkbMultiLineString25D = -2147483643,
  wkbMultiPolygon25D = -2147483642,
  wkbGeometryCollection25D = -2147483641
}

}
