.TH "QwtEventPattern::MousePattern" 3 "Fri Apr 15 2011" "Version 6.0.0" "Qwt User's Guide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QwtEventPattern::MousePattern \- 
.PP
A pattern for mouse events.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qwt_event_pattern.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMousePattern\fP (int btn=Qt::NoButton, int st=Qt::NoButton)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBbutton\fP"
.br
.ti -1c
.RI "int \fBstate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A pattern for mouse events. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QwtEventPattern::MousePattern::MousePattern (intbtn = \fCQt::NoButton\fP, intst = \fCQt::NoButton\fP)\fC [inline]\fP"
.PP
Constructor. 
.SH "Member Data Documentation"
.PP 
.SS "int \fBQwtEventPattern::MousePattern::button\fP"
.PP
Button code. 
.SS "int \fBQwtEventPattern::MousePattern::state\fP"
.PP
State. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Qwt User's Guide from the source code.
