.TH "QwtEventPattern::KeyPattern" 3 "Fri Apr 15 2011" "Version 6.0.0" "Qwt User's Guide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QwtEventPattern::KeyPattern \- 
.PP
A pattern for key events.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qwt_event_pattern.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKeyPattern\fP (int k=0, int st=Qt::NoButton)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBkey\fP"
.br
.ti -1c
.RI "int \fBstate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A pattern for key events. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QwtEventPattern::KeyPattern::KeyPattern (intk = \fC0\fP, intst = \fCQt::NoButton\fP)\fC [inline]\fP"
.PP
Constructor. 
.SH "Member Data Documentation"
.PP 
.SS "int \fBQwtEventPattern::KeyPattern::key\fP"
.PP
Key code. 
.SS "int \fBQwtEventPattern::KeyPattern::state\fP"
.PP
State. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Qwt User's Guide from the source code.
