.TH "QwtPickerDragPointMachine" 3 "Fri Apr 15 2011" "Version 6.0.0" "Qwt User's Guide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QwtPickerDragPointMachine \- 
.PP
A state machine for point selections.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qwt_picker_machine.h>\fP
.PP
Inherits \fBQwtPickerMachine\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQwtPickerDragPointMachine\fP ()"
.br
.ti -1c
.RI "virtual QList< \fBCommand\fP > \fBtransition\fP (const \fBQwtEventPattern\fP &, const QEvent *)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A state machine for point selections. 

Pressing QwtEventPattern::MouseSelect1 or QwtEventPattern::KeySelect1 starts the selection, releasing QwtEventPattern::MouseSelect1 or a second press of QwtEventPattern::KeySelect1 terminates it. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QwtPickerDragPointMachine::QwtPickerDragPointMachine ()"
.PP
Constructor. 
.SH "Member Function Documentation"
.PP 
.SS "QList< \fBQwtPickerMachine::Command\fP > QwtPickerDragPointMachine::transition (const \fBQwtEventPattern\fP &eventPattern, const QEvent *e)\fC [virtual]\fP"
.PP
Transition. 
.PP
Implements \fBQwtPickerMachine\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for Qwt User's Guide from the source code.
