.TH "QwtSetSample" 3 "Fri Apr 15 2011" "Version 6.0.0" "Qwt User's Guide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QwtSetSample \- 
.PP
A sample of the types (x1...xn, y) or (x, y1..yn)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qwt_series_data.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQwtSetSample\fP ()"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBQwtSetSample\fP &other) const "
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBQwtSetSample\fP &other) const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBvalue\fP"
.br
.ti -1c
.RI "QVector< double > \fBset\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A sample of the types (x1...xn, y) or (x, y1..yn) 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QwtSetSample::QwtSetSample ()\fC [inline]\fP"Constructor The value is set to 0.0 
.SH "Member Function Documentation"
.PP 
.SS "bool QwtSetSample::operator!= (const \fBQwtSetSample\fP &other) const\fC [inline]\fP"
.PP
Compare operator. 
.SS "bool QwtSetSample::operator== (const \fBQwtSetSample\fP &other) const\fC [inline]\fP"
.PP
Compare operator. 
.SH "Member Data Documentation"
.PP 
.SS "QVector<double> \fBQwtSetSample::set\fP"
.PP
Vector of values associated to value. 
.SS "double \fBQwtSetSample::value\fP"
.PP
value 

.SH "Author"
.PP 
Generated automatically by Doxygen for Qwt User's Guide from the source code.
