.TH "spectrogramscreenshots" 3 "Fri Apr 15 2011" "Version 6.0.0" "Qwt User's Guide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
spectrogramscreenshots \- .TH "spectrogramscreenshots" 3 "Fri Apr 15 2011" "Version 6.0.0" "Qwt User's Guide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
spectrogramscreenshots \- .PP
.PP
.PP
/*! 
